### ISSUE TITLE
glowing-pumpkin-xiao-bff.ino 

### ISSUE THREAD

**Issue by huster-songtao** [johnwargo/glowing-pumpkin-xiao-bff#1]
**Describe the bug**
I open glowing-pumpkin-xiao-bff.ino using Arduino IDE and build the code.

In file included from d:\Arduino\Sketchbook\libraries\FastLED\src/FastLED.h:75,
                 from D:\Github\glowing-pumpkin-xiao-bff\glowing-pumpkin-xiao-bff.ino:33:
d:\Arduino\Sketchbook\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

exit status 1

Compilation error: exit status 1

**To Reproduce**
1. Git clone https://github.com/johnwargo/glowing-pumpkin-xiao-bff.git
2. Go to Arduino IDE 2.2.1 and open glowing-pumpkin-xiao-bff.ino
3. build glowing-pumpkin-xiao-bff.ino

**Expected behavior**
No hardware SPI pins defined.  All SPI access will default to bitbanged output

**Screenshots**
![20231108154111](https://github.com/johnwargo/glowing-pumpkin-xiao-bff/assets/94954133/1812171e-effa-4336-aed7-8f64929af002)

**Comment by johnwargo** [comment]
Hmmm, I've never seen that error and I have the same version of the Arduino IDE and FastLED library. When I compile, I get the following:

```
In file included from c:\Users\john\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from D:\dev\hardware\xiao\glowing-pumpkin-xiao-bff\glowing-pumpkin-xiao-bff.ino:11:
c:\Users\john\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Sketch uses 242293 bytes (7%) of program storage space. Maximum is 3342336 bytes.
Global variables use 18680 bytes (5%) of dynamic memory, leaving 309000 bytes for local variables. Maximum is 327680 bytes.
```

I built it and deployed to a device yesterday with no issues. I made some minor changes after that and just compiled it again to generate that example above. 

Which device are you using? I'm using this one: https://www.seeedstudio.com/XIAO-ESP32S3-p-5627.html. Those are all FastLED errors, you should check on the FastLED Forums.

**Comment by huster-songtao** [comment]
[XIAO-ESP32C3](https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/)

**Comment by huster-songtao** [comment]
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4038855e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x458
load:0x403cc710,len:0x814
load:0x403ce710,len:0x2878
entry 0x403cc710

The symbolic names for the 4 analogue pins
 A0 = 2
 A1 = 3
 A2 = 4
 A3 = 5

The symbolic names for the 11 digital pins
 D0 = 2
 D1 = 3
 D2 = 4
 D3 = 5
 D4 = 6
 D5 = 7
 D6 = 21
 D7 = 20
 D8 = 8
 D9 = 9
D10 = 10

**Comment by johnwargo** [comment]
That's a different architecture (RISC-V), I haven't tried it with this code. I have one I can test it on, but I am out of town and won't be able to get to it until Sunday at the earliest.  I just did a quick search and there seems to be a lot of issues with FastLED and the C3 family of ESP32 processors. 

I will let you know what I find out when I test this. You should really ask on the FastLED forums too.

**Comment by huster-songtao** [comment]
When I started with Seeed Studio XIAO ESP32C3 and FastLed, There is no good way to light up the WS2812B light strip.
Nice to see you using XIAO-ESP32S3, You are the only developer I find and have seen who uses the Xiao ESP32 board and has open source code. I am very happy and I am not alone

```
/*********************************************************
* Glowing Pumpkin 
* 
* Xaio ESP32 S3 version using the Adafruit 5x5 BFF LED
* Matrix.
*
* By John M. Wargo
* https://johnwargo.com
**********************************************************/

#include <FastLED.h>

#define DEBUG true
#define DELAY_MIN 5000
#define DELAY_MAX 10000
#define NUM_LEDS 64
#define PIN D10

int numColors = 6;
uint32_t colors[] = { CRGB::Blue, CRGB::Green, CRGB::Orange, CRGB::Purple, CRGB::Red, CRGB::Yellow };
CRGB leds[NUM_LEDS];  // LED Array (internal memory structure from FastLED)

void setup() {
  // Initialize the FastLED library
  FastLED.addLeds<NEOPIXEL, PIN>(leds, NUM_LEDS);
  delay(500);  
}

void loop() {
  // Otherwise switch to the new color
  fadeColor(colors[(int)random(1, numColors + 1)]);
  delay(100);  
}

// Fill the NeoPixel array with a specific color
void fadeColor(CRGB c) {
  for (int i = 0; i < 25; i++) {
    leds[i] = c;
    FastLED.show();
    delay(10);
  }  
}
```

In file included from d:\Arduino\Sketchbook\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\tao\AppData\Local\Temp\.arduinoIDE-unsaved20231010-37848-1wd3ek4.3yjm\sketch_nov10d\sketch_nov10d.ino:11:
d:\Arduino\Sketchbook\libraries\FastLED\src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

exit status 1

Compilation error: exit status 1

The abnormal information above is very maddening. Searching for Bing and Google did not find a solution, nor did they find any code examples that could run.

**Comment by huster-songtao** [comment]
\Arduino\Sketchbook\libraries\FastLED\release_notes.md

> FastLED 3.4.0
> * Merged in contributed support for Seeedstudio Odyssey and XIAO boards

Arduino\Sketchbook\libraries\FastLED\src\platforms\arm\d21\fastpin_arm_d21.h

> #elif defined(SEEED_XIAO_M0)
> 
> #define MAX_PIN 10
> _FL_DEFPIN( 0, 2,0); _FL_DEFPIN( 1, 4,0); _FL_DEFPIN( 2,10,0); _FL_DEFPIN( 3,11,0);
> _FL_DEFPIN( 4, 8,0); _FL_DEFPIN( 5, 9,0); _FL_DEFPIN( 6, 8,1); _FL_DEFPIN( 7, 9,1);
> _FL_DEFPIN( 8, 7,0); _FL_DEFPIN( 9, 5,0); _FL_DEFPIN(10, 6,0);
> 
> #define SPI_DATA 9
> #define SPI_CLOCK 8
> 
> #define HAS_HARDWARE_PIN_SUPPORT 1
> 

I added code such as:
```
/*********************************************************
* Glowing Pumpkin 
* 
* Xaio ESP32 S3 version using the Adafruit 5x5 BFF LED
* Matrix.
*
* By John M. Wargo
* https://johnwargo.com
**********************************************************/

#define FASTLED_INTERNAL //remove annoying pragma messages
#define SEEED_XIAO_M0
#include <FastLED.h>

#define DEBUG true
#define DELAY_MIN 5000
#define DELAY_MAX 10000
#define NUM_LEDS 64
#define PIN D10

int numColors = 6;
uint32_t colors[] = { CRGB::Blue, CRGB::Green, CRGB::Orange, CRGB::Purple, CRGB::Red, CRGB::Yellow };
CRGB leds[NUM_LEDS];  // LED Array (internal memory structure from FastLED)

void setup() {
  // Initialize the FastLED library
  FastLED.addLeds<NEOPIXEL, PIN>(leds, NUM_LEDS);
  delay(500);  
}

void loop() {
  // Otherwise switch to the new color
  fadeColor(colors[(int)random(1, numColors + 1)]);
  delay(100);  
}

// Fill the NeoPixel array with a specific color
void fadeColor(CRGB c) {
  for (int i = 0; i < 25; i++) {
    leds[i] = c;
    FastLED.show();
    delay(10);
  }  
}
```

d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In member function 'void ESP32RMTController::startOnChannel(int)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:266:29: error: 'RMTMEM' was not declared in this scope
  266 |         mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
      |                             ^~~~~~
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp: In static member function 'static void ESP32RMTController::doneOnChannel(rmt_channel_t, void*)':
d:\Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp:347:5: error: 'gpio_matrix_out' was not declared in this scope; did you mean 'gpio_iomux_out'?
  347 |     gpio_matrix_out(pController->mPin, 0x100, 0, 0);
      |     ^~~~~~~~~~~~~~~
      |     gpio_iomux_out

exit status 1

Compilation error: exit status 1

```
#define FASTLED_INTERNAL //remove annoying pragma messages
#define SEEED_XIAO_M0
```
The above code brings new problems.

I find the code in \Arduino\Sketchbook\libraries\FastLED\src\platforms\esp\32\clockless_rmt_esp32.cpp
```
    if (FASTLED_RMT_BUILTIN_DRIVER) {
        // -- Use the built-in RMT driver to send all the data in one shot
        rmt_register_tx_end_callback(doneOnChannel, 0);
        rmt_write_items(mRMT_channel, mBuffer, mBufferSize, false);
    } else {
        // -- Use our custom driver to send the data incrementally

        // -- Initialize the counters that keep track of where we are in
        //    the pixel data and the RMT buffer
        mRMT_mem_start = & (RMTMEM.chan[mRMT_channel].data32[0].val);
        mRMT_mem_ptr = mRMT_mem_start;
        mCur = 0;
        mWhichHalf = 0;
        mLastFill = 0;

        // -- Fill both halves of the RMT buffer (a totaly of 64 bits of pixel data)
        fillNext(false);
        fillNext(false);

        // -- Turn on the interrupts
        espErr = rmt_set_tx_intr_en(mRMT_channel, true);
        FASTLED_DEBUG("rmt_set_tx_intr_en result: %d", espErr);

        // -- Kick off the transmission
        tx_start();
    }
```

**Comment by johnwargo** [comment]
OK, I just compiled the sketch for the Xiao ESP32-C3 and it compiled just fine:

```
In file included from c:\Users\john\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from D:\dev\hardware\xiao\glowing-pumpkin-xiao-bff\glowing-pumpkin-xiao-bff.ino:11:
c:\Users\john\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c: In function 'uartSetPins':
C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c:153:9: warning: 'return' with no value, in function returning non-void
         return;
         ^~~~~~
C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c:149:6: note: declared here
 bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, int8_t rtsPin)
      ^~~~~~~~~~~
Sketch uses 225380 bytes (17%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13900 bytes (4%) of dynamic memory, leaving 313780 bytes for local variables. Maximum is 327680 bytes.
```

So I'm not experiencing the same issue you are.  Have you checked to make sure you have the latest libraries?

**Comment by huster-songtao** [comment]
> OK, I just compiled the sketch for the Xiao ESP32-C3 and it compiled just fine:
> 
> ```
> In file included from c:\Users\john\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
>                  from D:\dev\hardware\xiao\glowing-pumpkin-xiao-bff\glowing-pumpkin-xiao-bff.ino:11:
> c:\Users\john\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
>  #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
>                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c: In function 'uartSetPins':
> C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c:153:9: warning: 'return' with no value, in function returning non-void
>          return;
>          ^~~~~~
> C:\Users\john\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\cores\esp32\esp32-hal-uart.c:149:6: note: declared here
>  bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, int8_t rtsPin)
>       ^~~~~~~~~~~
> Sketch uses 225380 bytes (17%) of program storage space. Maximum is 1310720 bytes.
> Global variables use 13900 bytes (4%) of dynamic memory, leaving 313780 bytes for local variables. Maximum is 327680 bytes.
> ```
> 
> So I'm not experiencing the same issue you are. Have you checked to make sure you have the latest libraries?

Could you post your *.ino code?
I am sure I have the latest libraries.

**Comment by johnwargo** [comment]
My `.ino` code is the code in this repo, they're exactly the same.

**Comment by huster-songtao** [comment]
```
/*********************************************************
* Glowing Pumpkin 
* 
* Xaio ESP32 S3 version using the Adafruit 5x5 BFF LED
* Matrix.
*
* By John M. Wargo
* https://johnwargo.com
**********************************************************/

#define FASTLED_INTERNAL //remove annoying pragma messages
// #define SEEED_XIAO_M0
// #define FASTLED_RMT_BUILTIN_DRIVER
// #define FASTLED_FORCE_SOFTWARE_SPI
// #define FASTLED_ESP32_I2S true
// #define FASTLED_RMT_MAX_CHANNELS 1
#include <FastLED.h>

#define DEBUG true
#define DELAY_MIN 5000
#define DELAY_MAX 10000
#define NUM_LEDS 64
#define PIN D10

int numColors = 6;
uint32_t colors[] = { CRGB::Blue, CRGB::Green, CRGB::Orange, CRGB::Purple, CRGB::Red, CRGB::Yellow };
CRGB leds[NUM_LEDS];  // LED Array (internal memory structure from FastLED)

void setup() {
  // Initialize the FastLED library
  FastLED.addLeds<NEOPIXEL, PIN>(leds, NUM_LEDS);
  delay(500);  
}

void loop() {
  // Otherwise switch to the new color
  fadeColor(colors[(int)random(1, numColors + 1)]);
  delay(100);  
}

// Fill the NeoPixel array with a specific color
void fadeColor(CRGB c) {
  for (int i = 0; i < 25; i++) {
    leds[i] = c;
    FastLED.show();
    delay(10);
  }  
}
```

I am using 3.0.0-alpha2 of the Arduino for esp32 by Espressif Systems.
It looks like FastLED is affected by a bug: [FastLED/FastLED#1553](https://github.com/FastLED/FastLED/issues/1553)
So i got errors.

I am using version [2.0.13](https://github.com/srwi/FastLEDHub/issues/17) successfully.
